os: linux
language: cpp
sudo: required
dist: trusty
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - libtbb-dev

before_install:
  - sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install cmake

before_script:
  - export CXX="g++-5"
  - export CC="gcc-5"
  - mkdir build
  - cd build

script:
  - cmake .. && make
